/**
 * The error code registry (agent operator contract v1, A2). Every literal
 * code thrown in `src/` has one entry here: its class (which derives the CLI
 * exit code and `retryable`), a one-sentence meaning, and optionally a
 * default suggestion, a default fix (diagnostic reads only), reasons, a docs
 * anchor and the frozen legacy wire value. `docs/guides/error-codes.md` is
 * generated from this table (`bun run build:error-codes`), and
 * `test/error-catalogue.test.ts` walks the source AST so an unregistered code
 * fails CI.
 *
 * Adding a code: add one entry (snake_case, no transport prefix), then run
 * `bun run build:error-codes`. Entries default their docs to
 * `docs/guides/error-codes.md#<code>`.
 */
import type { Action, Actor, Effect, ErrorClass } from './agent-output.ts';

export interface CodeEntry {
  class: ErrorClass;
  /** What happened, one sentence. */
  summary: string;
  /** Why it happens / what it protects. */
  why?: string;
  /** Closed vocabulary for `reason` when one code covers several causes. */
  reasons?: readonly string[];
  /** Repo-relative anchor; default `docs/guides/error-codes.md#<code>`. */
  docs?: string;
  /** Default prose suggestion when a site supplies none. */
  suggestion?: string;
  /**
   * Default fix template: read-only diagnostics only (scanner-checked).
   * `{slug}`, `{source_id}`, `{request_id}`, `{operation}` placeholders are
   * filled from envelope/receipt fields at render time; an unfillable
   * template is dropped, never rendered with a placeholder.
   */
  fix?: Action;
  effects?: readonly Effect[];
  actor?: Actor;
  /** The code this one replaced (documented in error-codes.md "Legacy `error` values"). */
  renamed_from?: string;
  /** Frozen v1 `error` wire value some sites keep for this canonical code. */
  legacy_error?: string;
  /** CLI exit code; default derives from class (1). */
  exit?: number;
  retryable?: boolean;
}

export const CODES = {
  access_command_failed: { class: 'caller', summary: "Google connect credential error: access command failed.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  access_denied_test_user: { class: 'host_only', summary: "Google connect credential error: access denied test user.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  access_env_missing: { class: 'caller', summary: "Google connect credential error: access env missing.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  acknowledgment_unavailable: { class: 'unavailable', summary: "This batch is unknown or outside the retained replay window." },
  admin_policy_enforced: { class: 'host_only', summary: "Google connect credential error: admin policy enforced.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  ambiguous_id: { class: 'caller', summary: "The legacy id matches multiple readable pages." },
  ambiguous_ref: { class: 'caller', summary: "A page reference in a rating matches pages in more than one source of that answer.", docs: 'docs/guides/retrieval-feedback.md#ambiguous_ref' },
  ambiguous_skill: { class: 'caller', summary: "This name belongs to multiple authorized sources." },
  answer_not_yours: { class: 'caller', summary: "The rated answer was returned to a different client.", docs: 'docs/guides/retrieval-feedback.md#answer_not_yours' },
  answer_pending: { class: 'retryable', summary: "The rated answer is still being recorded; retry in a few seconds.", docs: 'docs/guides/retrieval-feedback.md#answer_pending' },
  answer_unavailable: { class: 'caller', summary: "The rated answer is not recorded: unknown, dropped, or older than the retention window.", docs: 'docs/guides/retrieval-feedback.md#answer_unavailable' },
  api_not_enabled: { class: 'host_only', summary: "Google connect credential error: api not enabled.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  approval_required: { class: 'consent', summary: "The change needs the owner's explicit approval before it can proceed." },
  autopilot_job_owned_by_other_brain: { class: 'caller', summary: "The autopilot job is bound to a different brain." },
  benchmark_duplicate_task_id: { class: 'caller', summary: "Benchmark duplicate task id." },
  benchmark_empty: { class: 'caller', summary: "The benchmark file has no tasks." },
  benchmark_exists: { class: 'caller', summary: "A benchmark already exists at the target path." },
  benchmark_judge_llm_no_rubric: { class: 'caller', summary: "Benchmark judge llm no rubric." },
  benchmark_judge_qrels_no_expected: { class: 'caller', summary: "Benchmark judge qrels no expected." },
  benchmark_judge_rule_no_checks: { class: 'caller', summary: "Benchmark judge rule no checks." },
  benchmark_judge_unknown_kind: { class: 'caller', summary: "Benchmark judge unknown kind." },
  benchmark_malformed: { class: 'caller', summary: "A benchmark row is not valid JSON." },
  benchmark_missing_judge: { class: 'caller', summary: "Benchmark missing judge." },
  benchmark_missing_task: { class: 'caller', summary: "Benchmark missing task." },
  benchmark_missing_task_id: { class: 'caller', summary: "Benchmark missing task id." },
  benchmark_not_found: { class: 'caller', summary: "The benchmark file cannot be read." },
  benchmark_rule_check_bad_arg: { class: 'caller', summary: "Benchmark rule check bad arg." },
  benchmark_rule_check_malformed: { class: 'caller', summary: "Benchmark rule check malformed." },
  benchmark_rule_check_unknown_op: { class: 'caller', summary: "Benchmark rule check unknown op." },
  bootstrap_empty: { class: 'caller', summary: "The benchmark bootstrap produced no tasks." },
  bootstrap_pending_review: { class: 'caller', summary: "The bootstrapped benchmark awaits human review." },
  bridge_ownership_conflict: { class: 'caller', summary: "The private local CLI registration is invalid." },
  bucket_not_found: { class: 'unavailable', summary: "The configured storage bucket does not exist." },
  budget_unsatisfiable: { class: 'unavailable', summary: "Reserved by MEMORY_VERBS v1; never returned." },
  cache_quota_exceeded: { class: 'caller', summary: "Retained shared-skill revisions reached this installation's local cache quota.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  cancelled: { class: 'caller', summary: "The write was cancelled before it committed." },
  catalog_capacity_exceeded: { class: 'caller', summary: "The shared-skills catalog visible to this connection exceeds the delivery limits.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  catalog_unavailable: { class: 'retryable', summary: "Shared skill storage is not ready on this brain." },
  changed_since_preview: { class: 'caller', summary: "The file changed after its repair was previewed, so nothing was written.", why: "A repair writes exactly the bytes the operator approved; it binds approval to the previewed file hash and refuses when the file moved on.", suggestion: 'Preview the repair again, review the new proposal, and approve its new hash.' },
  chronicle_skipped: { class: 'unavailable', summary: "Automatic event extraction (auto_chronicle) skipped or failed this page; `reason` says why and `fix`, when present, is the next step.", reasons: ['auto_chronicle_off', 'auto_chronicle_invalid', 'slug_bound_client', 'operation_bound_client', 'no_extract', 'history', 'not_yet_happened', 'too_short', 'dream_generated', 'no_write_decision', 'not_chronicle_shaped', 'already_extracted', 'superseded', 'daily_limit', 'judge_llm_unavailable', 'no_pricing', 'budget_exhausted', 'judge_chat_error', 'judge_truncated', 'judge_parse_failed', 'malformed_proposal', 'publish_error', 'judge_refused', 'page_missing', 'no_events', 'future_dated', 'date_imprecise', 'no_chat_provider'], docs: 'docs/guides/life-chronicle.md#skip-and-failure-codes', suggestion: 'Read the receipt or doctor `auto_chronicle` check: its `why` explains the reason and its `fix`, when present, is the next step (paid fixes need the user\'s agreement).' },
  checkpoint_missing: { class: 'caller', summary: "The approved source plan is missing; do not restart from a different revision." },
  checkpoint_validation_timeout: { class: 'retryable', summary: "Validating the managed-sync checkpoint timed out." },
  claim_already_used: { class: 'caller', summary: "Google connect credential error: claim already used.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  client_json_unreadable: { class: 'caller', summary: "Google connect credential error: client json unreadable.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  client_json_wrong_type: { class: 'caller', summary: "Google connect credential error: client json wrong type.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  client_shape_invalid: { class: 'caller', summary: "Google connect credential error: client shape invalid.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  code_callees_requires_symbol: { class: 'caller', summary: "code-callees requires a symbol name." },
  code_callers_requires_symbol: { class: 'caller', summary: "code-callers requires a symbol name." },
  code_def_requires_symbol: { class: 'caller', summary: "code-def requires a symbol name." },
  code_refs_requires_symbol: { class: 'caller', summary: "code-refs requires a symbol name." },
  code_reused: { class: 'caller', summary: "Google connect credential error: code reused.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  colon_slug_windows_write_through: { class: 'caller', summary: "A colon slug cannot be written through on Windows." },
  command_failed: { class: 'server', summary: "The command failed before it wrote its JSON result." },
  config_error: { class: 'caller', summary: "A required configuration value or directory is missing or invalid." },
  confirmation_required: { class: 'consent', summary: "The command needs the user's authorization before it runs; nothing was changed.", exit: 3 },
  conflicting_source_scope: { class: 'caller', summary: "--source and --all-sources were both given." },
  connector_account_changed: { class: 'caller', summary: "The connector credential resolves to a different account than the source is pinned to." },
  connector_fence_below_timeline: { class: 'caller', summary: "A stored page carries a fence the connector render cannot preserve." },
  connector_holds_exhausted: { class: 'caller', summary: "The source holds the maximum number of failed items; its cursor did not advance." },
  connector_intent_outdated: { class: 'caller', summary: "The connector request no longer matches the stored connector intent." },
  consent_timeout: { class: 'consent', summary: "Google connect credential error: consent timeout.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  content_rejected: { class: 'caller', summary: "The content-sanity gate rejected the content because the operator set `content_sanity.junk_disposition` to `reject`.", why: "A junk-pattern or operator-literal hit is refused instead of quarantined under that setting, so the page was not written. The same content refuses on every retry.", suggestion: 'Remove the matched junk from the file, or switch `content_sanity.junk_disposition` back to `quarantine` (a user decision), then import it again.' },
  cost_cap_exceeded: { class: 'server', summary: "The run reached its cost cap before finishing." },
  cost_preview_requires_yes: { class: 'consent', summary: "Cost preview requires yes." },
  cycle_failed: { class: 'server', summary: "The maintenance (dream) cycle failed, or a phase threw and was contained so later phases could run." },
  d_sel_too_small: { class: 'caller', summary: "The selection split has too few tasks for meaningful validation." },
  database_error: { class: 'server', summary: "The brain database could not be reached or refused the operation." },
  demo_graph_failed: { class: 'server', summary: "The fictional graph did not verify." },
  demo_import_failed: { class: 'server', summary: "The fictional page did not import successfully." },
  demo_verification_failed: { class: 'server', summary: "Expected ownership or decision provenance is missing." },
  derived_cap_exhausted: { class: 'server', summary: "Paid work stopped at the cost cap derived from its estimate; the run is resumable." },
  destination_not_ready: { class: 'host_only', summary: "The destination brain is not initialized for this operation." },
  dirty_tree: { class: 'caller', summary: "Commit or stash canonical skill edits before optimization." },
  effect_not_failed: { class: 'caller', summary: "Only a failed, non-running embedding effect can be explicitly retried." },
  embedding_auth_failed: { class: 'unavailable', summary: "The embedding provider rejected the credentials." },
  embedding_budget_below_worst_case: { class: 'unavailable', summary: "The embedding migration cap is below its worst-case cost; nothing was changed." },
  embedding_configuration: { class: 'host_only', summary: "The brain's embedding configuration is invalid." },
  embedding_disabled: { class: 'unavailable', summary: "Embeddings are disabled on this brain." },
  embedding_failed: { class: 'server', summary: "Computing embeddings for the content failed." },
  embedding_model_mismatch: { class: 'unavailable', summary: "The configured provider does not match the active embedding column." },
  embedding_plane_split: { class: 'unavailable', summary: "Embedding plane split." },
  embedding_storage_unavailable: { class: 'retryable', summary: "Embedding policy or claim storage is temporarily unavailable." },
  embedding_unavailable: { class: 'unavailable', summary: "The provider returned an incomplete embedding batch." },
  embedding_unconfigured: { class: 'host_only', summary: "The selected brain has no verifiable text embedding model and dimensions." },
  embedding_width_mismatch: { class: 'caller', summary: "The embedding model cannot produce the width of the brain's vector column; nothing was changed." },
  engine_graduated: { class: 'caller', summary: "A client opened a PGLite brain that moved to Postgres; its old path holds a tombstone.", docs: 'docs/guides/move-to-postgres.md#graduated-datastore' },
  eval_suite_unwired: { class: 'caller', summary: "`gbrain eval run-all` was asked for a suite it does not run in-process (longmemeval or replay); nothing ran.", why: "run-all runs only wired suites (brainbench). Recording a skipped run and exiting 0 would read as a completed sweep with no numbers behind it.", suggestion: 'Run each requested suite with its own command (`gbrain eval longmemeval <dataset.jsonl> --mode <mode> --record`, `gbrain eval replay --mode <mode>`), once per mode, or drop it from --suites.' },
  export_limit: { class: 'caller', summary: "This migration is bounded to 5,000 active pages per source; split or use a reviewed bulk export." },
  extraction_failed: { class: 'server', summary: "The accepted atom extraction produced malformed output." },
  extractor_identity_mismatch: { class: 'server', summary: "The approved extractor differs from the installed extractor; this receipt cannot resume or admit another revision." },
  fact_already_expired: { class: 'caller', summary: "The fact had already expired before this write." },
  fact_not_found: { class: 'caller', summary: "Fact not found." },
  facts_absorb_write_refused: { class: 'caller', summary: "Facts absorb refused the write." },
  facts_drain_deferred: { class: 'unavailable', summary: "The automatic facts drain left queued facts-absorb jobs waiting; `reason` says why and `fix`, when present, is the next step. Nothing is dropped: the jobs run on a later drain.", reasons: ['no_key', 'extraction_unavailable', 'budget_exhausted', 'daily_budget_exhausted', 'job_over_budget', 'no_pricing', 'provider_halted', 'drain_error'], docs: 'docs/guides/facts-drain.md#deferrals', suggestion: 'Read doctor `facts_drain`: its message names the cause and its fix the next step (raising a spend cap is paid; ask the user first).', fix: { argv: ['gbrain', 'doctor', '--only', 'facts_drain', '--json'], consent: [], actor: 'agent', why: 'Shows the drain status, the backlog and the last error with its fix.', requires_exclusive: false } },
  facts_drain_job_failed: { class: 'server', summary: "A facts-absorb job failed inside the automatic facts drain; it retries with backoff until its attempts run out.", docs: 'docs/guides/facts-drain.md#deferrals', suggestion: 'Read doctor `facts_drain`: its message names the cause and its fix the next step (raising a spend cap is paid; ask the user first).', fix: { argv: ['gbrain', 'doctor', '--only', 'facts_drain', '--json'], consent: [], actor: 'agent', why: 'Shows the drain status, the backlog and the last error with its fix.', requires_exclusive: false } },
  facts_payload_expired: { class: 'server', summary: "The accepted fact extraction failed and its retained payload has expired." },
  feedback_disabled: { class: 'host_only', summary: "Retrieval feedback is off (or not learning) on this brain, so ratings are not recorded.", docs: 'docs/guides/retrieval-feedback.md#feedback_disabled' },
  feedback_not_authorized: { class: 'host_only', summary: "This caller may not change the brain's shared ranking for that source.", docs: 'docs/guides/retrieval-feedback.md#feedback_not_authorized' },
  fetch_failed: { class: 'retryable', summary: "Fetching the upstream failed." },
  file_too_large: { class: 'caller', summary: "The file is over the import size limit (5 MB for Markdown and code, 10 MiB for any sync read), so it was not imported.", why: "Size limits bound parsing, chunking and embedding cost. The same bytes refuse on every retry.", suggestion: 'Split the file into smaller files, or leave it out of the source (sync.exclude), then sync or import again.' },
  follow_approval_required: { class: 'caller', summary: "Following a brain's shared skills needs the user's explicit follow approval.", docs: 'docs/guides/shared-brain-skills.md#approve-publication-following-and-editing-separately' },
  frontmatter_slug_conflict: { class: 'caller', summary: "The file's frontmatter `slug:` names a different page than its path does.", why: "The path decides a file's page; a conflicting declared slug would overwrite or fork another page, so the file is refused until one of them changes.", suggestion: 'Remove the `slug:` line or make it match the path, then commit and sync again.' },
  full_resync_required: { class: 'retryable', summary: "The catalog cursor is invalid or expired." },
  gate_failed: { class: 'caller', summary: "The eval gate found retrieval regressions or correctness below its thresholds." },
  git_index_locked: { class: 'retryable', summary: "Another Git process holds the canonical checkout index lock." },
  git_index_stale: { class: 'caller', summary: "Git index stale." },
  git_push_unavailable: { class: 'retryable', summary: "The canonical commit is durable locally; its push will retry." },
  git_target_unsafe: { class: 'caller', summary: "Git cannot identify the existing canonical file by its native spelling." },
  git_unavailable: { class: 'retryable', summary: "A git command did not complete." },
  graduation_drain_timeout: { class: 'retryable', summary: "Queued or running writes did not drain within --drain-timeout; the move stopped before copying and the source is unchanged.", docs: 'docs/guides/move-to-postgres.md#drain', reasons: ['progressing', 'blocked'], exit: 11 },
  graduation_embedding_dimension_mismatch: { class: 'caller', summary: "An existing, non-empty target database has a different embedding column layout than the brain being moved.", docs: 'docs/guides/move-to-postgres.md#embeddings' },
  graduation_foreign_host_binding: { class: 'host_only', summary: "A source's worktree is owned by another host, so this host cannot move it to Postgres.", docs: 'docs/guides/move-to-postgres.md#hosts' },
  graduation_in_progress: { class: 'retryable', summary: "Another process is moving this brain to Postgres; neither engine may be opened until it finishes.", docs: 'docs/guides/move-to-postgres.md#in-progress', exit: 75 },
  graduation_interrupted: { class: 'unavailable', summary: "An engine graduation stopped before it finished and no process owns it.", docs: 'docs/guides/move-to-postgres.md#resume' },
  graduation_rollback_writes_lost: { class: 'consent', summary: "Rolling back to PGLite would drop changes made on Postgres since the move.", docs: 'docs/guides/move-to-postgres.md#rollback', reasons: ['user_data', 'security_changes'] },
  graduation_source_writer_held: { class: 'host_only', summary: "A live serve or daemon holds the PGLite brain and did not hand it over to the move.", docs: 'docs/ENGINES.md#graduation-writer-held' },
  graduation_split_brain: { class: 'unavailable', summary: "A different brain appeared at the graduated brain's old path; the target is withheld from authority until the user decides.", docs: 'docs/guides/move-to-postgres.md#split-brain' },
  graduation_target_auth_failed: { class: 'caller', summary: "The target database rejected the credentials recorded for this move.", docs: 'docs/guides/move-to-postgres.md#credentials' },
  graduation_target_ddl_unreachable: { class: 'unavailable', summary: "The target's direct (schema) connection is unreachable or names a different database than its main URL.", docs: 'docs/guides/move-to-postgres.md#ddl-connection' },
  graduation_target_not_empty: { class: 'caller', summary: "The target database already holds data that is not this move's.", docs: 'docs/guides/move-to-postgres.md#target-not-empty' },
  graduation_target_unsupported: { class: 'caller', summary: "The target database is missing a prerequisite (server version, vector extension with halfvec, CREATE privilege or a matching column).", docs: 'docs/guides/move-to-postgres.md#target-requirements', reasons: ['server_version', 'vector', 'halfvec', 'create_privilege', 'column', 'env_override'] },
  graduation_unclassified_table: { class: 'server', summary: "A database has a relation the graduation inventory does not classify, so moving it could lose data.", docs: 'docs/guides/move-to-postgres.md#inventory', reasons: ['newer_schema', 'missing_inventory_row'] },
  graduation_unsupported_platform: { class: 'host_only', summary: "Moving a brain with write history to Postgres is not available on this platform yet.", docs: 'docs/guides/move-to-postgres.md#platforms' },
  graduation_verify_failed: { class: 'server', summary: "The moved copy did not verify against the source; the target stays fenced and the source stays authoritative.", docs: 'docs/guides/move-to-postgres.md#verify', reasons: ['count', 'digest', 'sequence', 'fk', 'trigger', 'relation_set', 'replay', 'doctor'] },
  graph_incomplete: { class: 'server', summary: "Source relationship reconciliation is incomplete." },
  held_out_overlaps_benchmark: { class: 'caller', summary: "Held out overlaps benchmark." },
  held_out_required_for_bundled: { class: 'caller', summary: "Held out required for bundled." },
  idempotency_conflict: { class: 'caller', summary: "The request_id already belongs to a different accepted operation." },
  independent_principal_required: { class: 'consent', summary: "This local CLI principal already owns another source/destination for this harness." },
  insufficient_scope: { class: 'host_only', summary: "The connection lacks the OAuth scope the operation requires.", legacy_error: 'permission_denied' },
  internal: { class: 'server', summary: "A memory verb failed on the server; this is not a caller mistake." },
  internal_error: { class: 'server', summary: "The server failed while running the operation; this is not a caller mistake." },
  interrupted: { class: 'server', summary: "The operation was interrupted by a signal before it finished.", exit: 130 },
  invalid_acknowledgment: { class: 'caller', summary: "The shared-skills delivery acknowledgment does not match a batch issued to this enrollment.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  invalid_client: { class: 'caller', summary: "Google connect credential error: invalid client.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_connector_text: { class: 'caller', summary: "Invalid connector text." },
  invalid_frontmatter: { class: 'caller', summary: "The file's YAML frontmatter cannot be read without guessing, so it was not imported.", why: "gbrain imports frontmatter it can read exactly (quoting an unquoted value at most). Guessing could store a wrong title, merge a duplicate, or read a protected key such as `visibility` as a broader value.", reasons: ['yaml_parse', 'needs_interpretation', 'ambiguous_identity_key', 'ambiguous_protected_key'], suggestion: 'Fix the named line in the file (one line per key, the whole value quoted), then commit and sync or import again.' },
  invalid_grant_clock_skew: { class: 'caller', summary: "Google connect credential error: invalid grant clock skew.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_grant_revoked: { class: 'caller', summary: "Google connect credential error: invalid grant revoked.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_grant_testing_expiry: { class: 'caller', summary: "Google connect credential error: invalid grant testing expiry.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  invalid_params: { class: 'caller', summary: "A parameter is missing, has the wrong type, or has an invalid value.", exit: 2 },
  invalid_rating: { class: 'caller', summary: "A rating must be an integer from 1 to 5.", docs: 'docs/guides/retrieval-feedback.md#invalid_rating' },
  invalid_receipt: { class: 'server', summary: "A company-source ingestion receipt input failed validation inside gbrain; nothing was written.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  invalid_receipt_transition: { class: 'caller', summary: "An ingestion receipt cannot skip a phase or complete while files failed, writes are pending or verification failed.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  invalid_request: { class: 'caller', summary: "submit_agent over the local CLI: use `gbrain agent run` instead." },
  invalid_source: { class: 'caller', summary: "The source argument or source state is invalid for this operation." },
  invalid_source_pin: { class: 'caller', summary: "The .gbrain-source pin names an invalid source id." },
  invalid_source_uri: { class: 'caller', summary: "The page has a stored file source_uri that cannot be resolved to a local filesystem path." },
  invalid_token: { class: 'host_only', summary: "The bearer token is missing, invalid, or revoked." },
  invalid_write_wait: { class: 'caller', summary: "Invalid write wait." },
  legacy_job_selection_invalid: { class: 'caller', summary: "The legacy job selection is invalid." },
  legacy_jobs_active: { class: 'caller', summary: "Legacy jobs are still active." },
  local_conflict: { class: 'caller', summary: "A local file or registration conflicts with the requested change." },
  lock_busy: { class: 'retryable', summary: "Another process holds the lock this command needs." },
  managed_pull_skipped: { class: 'retryable', summary: "The managed pull was skipped." },
  membership_inactive: { class: 'caller', summary: "The shared-skills enrollment epoch was left or superseded.", docs: 'docs/guides/shared-brain-skills.md#membership-inactive-after-a-re-enrollment' },
  membership_not_found: { class: 'caller', summary: "This principal has no shared-skills membership with that installation id.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  method_not_allowed: { class: 'caller', summary: "The HTTP method is not allowed on this endpoint." },
  migration_failed: { class: 'server', summary: "A migration orchestrator failed, so the migration chain stopped; finished migrations stay recorded.",
    reasons: ['orchestrator_failed', 'orchestrator_threw', 'ledger_write_failed', 'preview_failed', 'schema_failed'] },
  migrations_pending: { class: 'caller', summary: "Schema migrations are behind and this run did not apply them.",
    why: 'apply-migrations applies schema migrations only with --yes (or --non-interactive); without it the run reports the drift instead of claiming the brain is up to date.' },
  migrations_running: { class: 'retryable', summary: "Another apply-migrations run holds the migration orchestration lock.", exit: 75 },
  missing_source_scope: { class: 'server', summary: "A remote tool call reached dispatch without a resolved source scope; the shared default source is refused." },
  missing_source_value: { class: 'caller', summary: "A source flag was given without a value." },
  models_strict_violation: { class: 'caller', summary: "A configured model is not allowed under models strict mode." },
  no_pricing: { class: 'unavailable', summary: "gbrain has no price for the model, so a user-set cost cap cannot be enforced." },
  no_refresh_token: { class: 'caller', summary: "Google connect credential error: no refresh token.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  no_routing_eval: { class: 'caller', summary: "The skill has no routing-eval rows to bootstrap a benchmark from." },
  no_skill_md: { class: 'caller', summary: "The skill directory has no SKILL.md." },
  no_worker: { class: 'caller', summary: "No worker is running for this queue, so a queued job would wait until something runs it.", why: "PGLite brains have no background worker (the database is single-writer), and a Postgres queue needs a running `gbrain jobs work` or supervisor. Queuing without one leaves the job waiting with no error." },
  no_worker_surface: { class: 'caller', summary: "No worker surface." },
  not_a_git_repo: { class: 'caller', summary: "The source path must contain committed Git content." },
  not_connected: { class: 'caller', summary: "Google connect credential error: not connected.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  no_brain: { class: 'caller', summary: "No brain is configured on this machine.", suggestion: 'Run `gbrain init --pglite --no-embedding` to create a local keyless brain (or `gbrain init --help` for hosted and Postgres options).' },
  not_found: { class: 'caller', summary: "The requested resource does not exist or is not visible to this caller.", legacy_error: 'invalid_params' },
  overlapping_path: { class: 'caller', summary: "Sources cannot claim overlapping canonical directories." },
  owner_unavailable: { class: 'retryable', summary: "The brain's persistence owner is not reachable right now." },
  page_identity_changed: { class: 'caller', summary: "The page was deleted or replaced while the operation ran.", fix: { argv: ['gbrain', 'get', '--source', '{source_id}', '--', '{slug}'], mcp: { tool: 'get_page', arguments: { slug: '{slug}', source_id: '{source_id}' } }, consent: [], actor: 'agent', why: "Shows which page holds the slug now and its revision; a new attempt needs a new request_id.", requires_exclusive: false } },
  page_not_found: { class: 'caller', summary: "No page with that slug exists in the selected source.", legacy_error: 'page_identity_changed', fix: { argv: ['gbrain', 'get', '--source', '{source_id}', '--', '{slug}'], mcp: { tool: 'get_page', arguments: { slug: '{slug}', source_id: '{source_id}' } }, consent: [], actor: 'agent', why: "Confirms whether the page exists in this source before anything is recreated.", requires_exclusive: false } },
  parse_error: { class: 'caller', summary: "The request body is not valid JSON." },
  parser_regression: { class: 'server', summary: "A file whose exact bytes imported before is now refused by gbrain's frontmatter reader.", why: "The same bytes imported under an earlier gbrain version, so only gbrain changed; with `sync.parser_regression=hold` such a file is held and the rest of the sync continues.", suggestion: 'Report it as a gbrain bug with the gbrain version, the file and the code; upgrade or pin the last good version, then sync again with --retry-failed.' },
  pasted_wrong_url: { class: 'caller', summary: "Google connect credential error: pasted wrong url.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  payload_too_large: { class: 'caller', summary: "The payload exceeds the configured size cap." },
  pending_writes: { class: 'retryable', summary: "A pending source write prevents verified completion." },
  permission_denied: { class: 'host_only', summary: "This caller is not authorized for the operation." },
  pglite_busy: { class: 'retryable', summary: "Another gbrain process holds this PGLite brain's single-writer lock.", reasons: ['timeout', 'live_serve'], suggestion: 'Wait for the current command or server to close, then retry. Do not remove a live lock.' },
  plan_output_failed: { class: 'server', summary: "Writing the plan output failed." },
  plan_stale: { class: 'caller', summary: "The saved plan has no valid repository identity." },
  port_in_use: { class: 'retryable', summary: "Google connect credential error: port in use.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  preview_changed: { class: 'caller', summary: "The state changed since the approved preview." },
  profile_incompatible: { class: 'caller', summary: "The stored profile is incompatible with this operation." },
  projection_owner_resident: { class: 'host_only', summary: "A resident owner holds the projection." },
  projection_pending: { class: 'retryable', summary: "The current text projection is not ready." },
  provenance_required: { class: 'caller', summary: "provenance is required and must be non-empty." },
  publication_pending: { class: 'retryable', summary: "The catalog adoption is accepted but not fully committed." },
  queue_capacity: { class: 'retryable', summary: "The bounded queue is full; existing requests keep their place." },
  rate_limited: { class: 'retryable', summary: "The request was rate-limited; retry after the stated delay." },
  receipt_conflict: { class: 'retryable', summary: "The ingestion receipt changed since it was read.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  receipt_fence_changed: { class: 'caller', summary: "The managed owner, topology or source binding changed while the ingestion ran.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  receipt_fence_required: { class: 'host_only', summary: "Ingestion into a managed or bound source needs the worktree owner's fence.", docs: 'docs/guides/company-brain-ingestion.md#resume-and-verify' },
  receipt_identity_mismatch: { class: 'caller', summary: "The receipt ID is already bound to different approved ingestion metadata.", docs: 'docs/guides/company-brain-ingestion.md#agent-and-ci-use' },
  recovery_required: { class: 'host_only', summary: "An earlier write left state that must be inspected and recovered before new writes." },
  redirect_uri_mismatch: { class: 'caller', summary: "Google connect credential error: redirect uri mismatch.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  ref_not_in_answer: { class: 'caller', summary: "The rated page is not one of the pages the answer used.", docs: 'docs/guides/retrieval-feedback.md#ref_not_in_answer' },
  refresh_dirty: { class: 'caller', summary: "The worktree has uncommitted changes." },
  refresh_diverged: { class: 'caller', summary: "The worktree diverged from its upstream; a fast-forward is impossible." },
  refresh_drain_timeout: { class: 'retryable', summary: "In-flight work did not drain before the refresh deadline." },
  refresh_no_upstream: { class: 'caller', summary: "The worktree has no upstream to refresh from." },
  refresh_not_managed: { class: 'host_only', summary: "The source is not managed, so it cannot be refreshed." },
  refresh_not_owner: { class: 'host_only', summary: "This process does not own the worktree it would refresh." },
  refresh_source_changed: { class: 'caller', summary: "The source changed during the refresh." },
  relay_disabled: { class: 'caller', summary: "Google connect credential error: relay disabled.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  relay_session_expired: { class: 'caller', summary: "Google connect credential error: relay session expired.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  relay_unreachable: { class: 'retryable', summary: "Google connect credential error: relay unreachable.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  rename_held: { class: 'caller', summary: "A renamed file is held because the page it was renamed from changed after the rename was recorded.", reasons: ['rename_source_changed'], why: "Moving the page now could carry the newer edit to the wrong file, so the rename waits for an explicit re-bind.", suggestion: 'Preview the frontmatter repair with --include-ambiguous to re-bind the rename to the current page, and approve it.' },
  request_already_submitted: { class: 'caller', summary: "This optimizer publication request has already been submitted." },
  request_too_large: { class: 'caller', summary: "The request exceeds a configured capacity; narrow it." },
  requirements_changed: { class: 'caller', summary: "The runtime requirements exceed the owner-approved publication policy." },
  requires_local_engine: { class: 'host_only', summary: "This command needs the brain's local database, and this install is a thin client of a remote brain." },
  response_too_large: { class: 'caller', summary: "Persistence response exceeds the local transport limit." },
  resume_spec_mismatch: { class: 'caller', summary: "Resume spec mismatch." },
  revision_conflict: { class: 'caller', summary: "The target changed since it was read; the expected revision no longer matches.", fix: { argv: ['gbrain', 'get', '--source', '{source_id}', '--', '{slug}'], mcp: { tool: 'get_page', arguments: { slug: '{slug}', source_id: '{source_id}' } }, consent: [], actor: 'agent', why: "Reads the current page and revision; resubmit against that revision with a new request_id.", requires_exclusive: false } },
  revision_required: { class: 'caller', summary: "Review the current policy and supply its expected_policy_epoch before changing disclosure." },
  revision_unavailable: { class: 'unavailable', summary: "The exact authorized revision is unavailable." },
  scope_denied: { class: 'host_only', summary: "The connection lacks the scope this memory verb requires." },
  scope_missing: { class: 'caller', summary: "Google connect credential error: scope missing.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  serve_port_in_use: { class: 'unavailable', summary: "gbrain serve --http could not listen: another process already holds that host and port.", suggestion: 'Stop the process on that port, or start the server with another --port and point the harnesses at it.' },
  serve_status_only: { class: 'unavailable', summary: "gbrain serve is in status-only mode: its brain is locked by another server, missing, damaged, or its config is unreadable.", reasons: ['lock_held', 'no_brain', 'config_unreadable', 'missing_brain', 'brain_unopenable', 'repair_failed', 'unavailable'], suggestion: 'Call gbrain_status for the cause, the fix and what to tell the user.' },
  shared_skills_unavailable: { class: 'unavailable', summary: "The shared-skills operation was refused." },
  shared_skills_unsupported: { class: 'unavailable', summary: "The server does not expose the shared-skills protocol." },
  skill_asset_not_found: { class: 'caller', summary: "The requested file is not in the approved revision manifest." },
  skill_bundle_required: { class: 'caller', summary: "Import cannot publish skill paths." },
  skill_candidate_invalid: { class: 'caller', summary: "The optimized candidate changed protected frontmatter or has an empty/invalid body." },
  skill_not_found: { class: 'caller', summary: "No authorized published skill matches this key." },
  skill_retention_capacity: { class: 'caller', summary: "Retained skill revisions exceed this source storage budget." },
  skill_unavailable: { class: 'caller', summary: "The qualified shared skill is not in this installation's current authorized view.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  source_binding_required: { class: 'caller', summary: "A write needs an explicit source binding on this MCP server (--source-guard)." },
  source_changed: { class: 'caller', summary: "The source changed during the operation; nothing was committed." },
  source_id_taken: { class: 'caller', summary: "This source already exists and does not match this exact admitted request." },
  source_not_ready: { class: 'caller', summary: "A committed source and approved schema are required." },
  source_profile_no_backfill: { class: 'unavailable', summary: "This source profile disables automatic embedding backfill." },
  source_referenced: { class: 'caller', summary: "OAuth clients still reference this source." },
  source_root_conflict: { class: 'caller', summary: "Multiple active sources alias this canonical skill root; resolve ownership before publishing." },
  source_writeback_required: { class: 'host_only', summary: "Canonical preparation requires a source-content correction; this profile never writes repository files." },
  split_bad_ratio: { class: 'caller', summary: "Split bad ratio." },
  split_unparseable: { class: 'caller', summary: "Split unparseable." },
  stale_unavailable: { class: 'unavailable', summary: "No complete, current authorized shared-skills view is available; cached shared skills stay unused.", docs: 'docs/guides/shared-brain-skills.md#troubleshoot-leave-and-recover' },
  state_mismatch: { class: 'caller', summary: "Google connect credential error: state mismatch.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  storage_error: { class: 'server', summary: "Reading or writing durable storage failed." },
  sync_not_applicable: { class: 'caller', summary: "Sync does not apply to this source: its directory is not a Git checkout.", why: "Sync imports changes between Git commits. A gbrain-owned content directory (created by init) holds files gbrain manages itself and is not a Git repository, so there is nothing to sync; gbrain never initializes Git on its own.", reasons: ['content_directory'] },
  sync_in_progress: { class: 'retryable', summary: "A sync is running on this source." },
  sync_parser_regression: { class: 'server', summary: "Sync stopped because gbrain would hold a file whose exact bytes imported before; this is a gbrain bug.", why: "The upgrade invariant says a newer reader never refuses bytes an older one imported, so the run stops without advancing rather than hide a regression.", suggestion: 'Report it with the gbrain version, the file and the code; upgrade or pin the last good version, then run gbrain sync --source <id> --no-pull --retry-failed.' },
  take_row_collision: { class: 'caller', summary: "A takes fence row number is already used by a different take that is not in this page's canonical fence." },
  target_escape: { class: 'caller', summary: "The skill target must remain within its selected root." },
  timeout: { class: 'retryable', summary: "The operation did not finish within its time bound.", exit: 124 },
  topology_change_required: { class: 'host_only', summary: "Adding this source would replace or overlap another owner root." },
  trusted_local_only: { class: 'host_only', summary: 'The operation runs only from the trusted local CLI on the brain host; no MCP connection can call it.', legacy_error: 'permission_denied', suggestion: 'Ask the user to run the named gbrain command on the brain host.' },
  unavailable: { class: 'unavailable', summary: "A required dependency or capability cannot serve this request." },
  unexpected_file_bytes: { class: 'server', summary: "A canonical skill file mode changed outside publication." },
  unexpected_staging_bytes: { class: 'server', summary: "Recovery staging has unexpected bytes or identity; the root and its recovery capacity remain reserved." },
  unknown: { class: 'server', summary: "An unclassified failure (legacy StructuredError fallback code)." },
  unknown_command: { class: 'caller', summary: "The CLI has no command by that name.", suggestion: 'Run `gbrain --help` for the command list.', exit: 2 },
  unknown_flag: { class: 'caller', summary: "The command does not accept one of the flags passed.", exit: 2 },
  unknown_method: { class: 'caller', summary: "The JSON-RPC method is not supported." },
  unknown_source: { class: 'caller', summary: "The named source is not registered or is archived." },
  unknown_tool: { class: 'caller', summary: "The named tool does not exist or is not callable on this connection.", legacy_error: 'unknown_operation' },
  unknown_transport: { class: 'unavailable', summary: "The caller's transport could not be identified." },
  unmanaged_path: { class: 'caller', summary: "Reclone only replaces a checkout created and managed by GBrain." },
  unsupported_export_data: { class: 'unavailable', summary: "The source contains data this export path cannot carry." },
  unsupported_mutation_protocol: { class: 'unavailable', summary: "Prepared mutation does not match its accepted target." },
  upstream: { class: 'retryable', summary: "Google connect credential error: upstream.", docs: 'docs/guides/google-connect.md#troubleshooting' },
  verification_failed: { class: 'server', summary: "Source content or relationships changed during verification." },
  withdrawal_capacity: { class: 'caller', summary: "Withdrawal capacity." },
  withdrawal_provenance: { class: 'server', summary: "The withdrawal target manifest is invalid." },
  write_claim_lost: { class: 'retryable', summary: "Execution claim changed before publication." },
  write_pending: { class: 'retryable', summary: "The write was accepted and is still pending; it may commit later.", exit: 10 },
  writer_admin_intent_required: { class: 'host_only', summary: "Topology changes require an action-specific --admin-intent and the --expected-state from a reviewed writer status." },
  writer_admin_locked: { class: 'host_only', summary: "Writer administration is locked; deactivation was not applied." },
  writer_admin_state_changed: { class: 'caller', summary: "Writer topology changed since inspection; the administrative request was not applied." },
  writer_busy: { class: 'retryable', summary: "The canonical worktree is busy with another write." },
  writer_coordinator_required: { class: 'host_only', summary: "The operation needs managed persistence (a writer coordinator) on the brain host." },
  writer_identity_invalid: { class: 'host_only', summary: "The local writer identity is invalid." },
  writer_identity_publish_failed: { class: 'host_only', summary: "The replacement writer is durable but its credential file could not be published." },
  writer_lock_unavailable: { class: 'retryable', summary: "Another activation probe is running." },
  writer_manifest_mismatch: { class: 'caller', summary: "Successor checkout differs from the recorded canonical manifest." },
  writer_manifest_unsafe: { class: 'caller', summary: "Canonical worktree transfer requires a symlink-free manifest." },
  writer_not_initialized: { class: 'host_only', summary: "Persistence identity is missing." },
  writer_not_quiesced: { class: 'host_only', summary: "Older writers or maintenance jobs are still running." },
  writer_pool_capacity: { class: 'retryable', summary: "Mirror recovery is waiting for publication capacity." },
  writer_registration_required: { class: 'host_only', summary: "Writer registration required." },
  writer_regrant_required: { class: 'host_only', summary: "This lane already has a different grant." },
  writer_transfer_conflict: { class: 'caller', summary: "Writer transfer conflict." },
  writer_transfer_required: { class: 'caller', summary: "Writer transfer required." },
  writer_upgrade_required: { class: 'host_only', summary: "Apply the canonical writer guard, outbox, and source lifecycle migrations before activation." },
  wrong_account_consented: { class: 'caller', summary: "Google connect credential error: wrong account consented.", docs: 'docs/guides/google-connect.md#troubleshooting' },
} as const satisfies Record<string, CodeEntry>;

export type RegistryCode = keyof typeof CODES;

/** One notice code (agent contract v1, A6). Lanes add producers' codes here. */
export interface NoticeEntry {
  kind: 'safety' | 'degraded' | 'coaching' | 'ask' | 'info';
  summary: string;
}

/** Notice codes. Mute (`gbrain notices mute`, `mute_notice`) accepts only coaching/info codes. */
export const NOTICE_CODES = {
  backup_coverage: { kind: 'coaching', summary: 'Some knowledge assets have no off-machine backup.' },
  empty_retrieval: { kind: 'info', summary: 'A retrieval returned no results; the notice says whether recall was degraded.' },
  first_run_decisions: { kind: 'ask', summary: 'init finished (or a stdio MCP session started on a brain with open decisions); the first-run decisions (search mode, writeback, harness wiring, skills) carry defaults the user may change. The one muteable ask.' },
  first_run_decisions_muted: { kind: 'info', summary: 'First-run decisions are still open, but the user muted them; the fix shows them again (`gbrain notices unmute first_run_decisions`).' },
  migrations_pending: { kind: 'safety', summary: 'Schema migrations are pending or failed to apply on this brain.' },
  no_worker: { kind: 'degraded', summary: 'A job was queued but no worker is running to execute it; it waits until a worker runs.' },
  unknown_param: { kind: 'info', summary: 'The call passed a parameter the tool does not declare; it was ignored.' },
  listing_truncated: { kind: 'info', summary: 'A listing returned a full page and more rows match; the fix is the next-page call.' },
  former_relationships_hidden: { kind: 'info', summary: 'A graph read returned live relationships only and left out ended ones; the fix repeats the call with status: "all" (or as_of) to see history.' },
  mention_index: { kind: 'degraded', summary: 'The entity mention index is pending, off, failed or does not cover this page type, so references listed for an entity may be incomplete.' },
  degraded_recall: { kind: 'degraded', summary: 'A retrieval stage that affects recall did not run; an empty or thin result is not proof of absence.' },
  source_binding_narrowed: { kind: 'info', summary: "A GBRAIN_SOURCE / .gbrain-source binding narrowed an unqualified read that came back empty; the fix reads another source explicitly." },
  degraded_dedup: { kind: 'info', summary: 'remember ran without an embedding provider, so only exact duplicates are detected.' },
  local_transcripts: { kind: 'info', summary: 'The brain host keeps recent session transcripts that page reads never return and this connection cannot read; the fix is the CLI read (`gbrain transcripts recent --json`).' },
  synthesis_keyless: { kind: 'info', summary: 'think returned gathered evidence without synthesis because no chat-model key is configured (by design on a keyless brain).' },
  think_not_saved: { kind: 'info', summary: 'think save/take persist only for the local CLI, so this answer was not saved.' },
  onboard_opportunities: { kind: 'coaching', summary: 'Onboarding checks found work that would improve this brain (gbrain onboard --check lists it).' },
  onboard_stale_chunks: { kind: 'coaching', summary: 'This search could not match chunks that have no embedding; the remedy is an embedding backfill (paid, ask first).' },
  onboard_link_coverage: { kind: 'coaching', summary: 'Few people/company pages have incoming links, so backlinks and graph answers are thin; the remedy is link extraction.' },
  onboard_timeline_coverage: { kind: 'coaching', summary: 'Few people/company pages have timeline entries, so dated answers are thin; the remedy is timeline extraction.' },
  onboard_no_takes: { kind: 'coaching', summary: 'The brain holds no takes, so think and recall cannot cite the user\'s own views; the remedy is recording or extracting takes.' },
  surface_env_invalid: { kind: 'info', summary: 'GBRAIN_SURFACE holds a value other than verbs, starter or full; the server ignored it and names the surface it serves.' },
  features_auto_fix: { kind: 'coaching', summary: 'gbrain features found auto-fixable gaps; the fix is the auto-fix command (it may spend on embeddings).' },
  post_upgrade: { kind: 'safety', summary: 'gbrain was upgraded; behavior for scripts and agents changed — read the behavior table once.' },
  facts_drain_first_run: { kind: 'info', summary: 'The automatic facts drain is about to process its first backlog on this brain: the queued page count, the estimated spend, the caps and the opt-out.' },
  facts_drain_deferred: { kind: 'degraded', summary: 'The automatic facts drain left queued pages waiting (no key, a spend cap, an unpriced model under a user cap); the fix is the next step.' },
  relational_chain: { kind: 'degraded', summary: 'A typed relationship chain found no complete answer (start page not visible, no typed edges, an empty hop) or hit a cap; the notice names the hop and the next call.' },
  held_files: { kind: 'degraded', summary: 'Sync holds files in the read scope it cannot import: held new files are missing and pages whose newer file is held are stale; the fix is the repair preview on the brain host.' },
  recovered_frontmatter: { kind: 'coaching', summary: 'Files imported only after quoting unquoted frontmatter values; the generator writing them should quote values (the fix is the repair preview).' },
} as const satisfies Record<string, NoticeEntry>;
